# Tensorflow

In [1]:
import tensorflow as tf
import numpy as np

In it's essence, tensorflow is a generic computing framework that allows you to define compute graphs (=definitions)
without running them at the same time - essentially splitting the time of computation definition from its execution.

Here's a hello world example: 

In [2]:
hello = tf.constant('Hello, TensorFlow!')
# To do anything useful in TF, you have the create a session and then run it
# This is also true for just outputting the value of a TF variable/constant/placeholder.
# While this is a trivial example to output the constant `hello`, 
# in real-world scenarios variables will be read from some dataset.
sess = tf.Session()  
print(sess.run(hello))

Hello, TensorFlow!


Let's do a simple calculation:

In [3]:
num1 = tf.constant(5, name="number1")
num2 = tf.constant(3, name="number2")
summation = tf.add(num1, num2) # 
sess = tf.Session()  
print "Using tf.add:", sess.run(summation)

# Note that tensorflow also does operator overload, so you can do this too:
result2 = num1 + num2
print "Using + operator:", sess.run(result2)

Using tf.add: 8
Using + operator: 8


In [4]:
# Under the hood, TF builds a graph ands adds operations to them, you can show that graph like so:
tf.get_default_graph().get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'number1' type=Const>,
 <tf.Operation 'number2' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'add' type=Add>]

Use **tf.placeholder** and TF sessions's **feed_dict** parameter if you want to specify the parameter values at execution time, like so:

In [5]:
num3 = tf.placeholder(dtype=np.int32) # dtype required for placeholder, uses numpy types
num4 = tf.placeholder(dtype=np.int32)
res = sess.run(num3 + num4, feed_dict={num3: 6, num4: 5})
print "6+5 =", res
res2 = sess.run(num3 + num4, {num3: 5, num4: 7})  # `feed_dict` keyword arg is optional (=2nd positional arg)
print "5+7 =", res2

# Note that feed_dict is actually taking `num3` and `num4` as dict keys: passing the objects themselves as keys.
# TF does some magic to make that work under the hood.

6+5 = 11
5+7 = 12


# Basic graph operations

Standard vector and matrix operations:

In [6]:
vec1 = tf.placeholder(dtype=np.int32)
vec2 = tf.placeholder(dtype=np.int32)
print "** VECTORS " + "*"* 50
print "addition", sess.run(vec1 + vec2, {vec1: [1, 2], vec2: [3, 4]})
print "element-wise multiplication", sess.run(vec1 * vec2, {vec1: [1, 2], vec2: [3, 4]})


print "** MATRICES " + "*"* 49
mat1 = tf.placeholder(shape=(2, 2), dtype=np.float64)
mat2 = tf.placeholder(shape=(2, 2), dtype=np.float64)
print "addition\n", sess.run(mat1 + mat2, {mat1: [ [1.1, 2.2], [3.3, 4.4]], mat2: [[5.5, 6.6], [7.7, 8.8]]})
print "element-wise multiplication\n", sess.run(mat1 * mat2, {mat1: [ [1.1, 2.2], [3.3, 4.4]], mat2: [[5.5, 6.6], [7.7, 8.8]]})
print "matrix multiplication\n", sess.run(tf.matmul(mat1, mat2), {mat1: [ [1.1, 2.2], [3.3, 4.4]], mat2: [[5.5, 6.6], [7.7, 8.8]]})

# print "element-wise multiplication", sess.run(vec1 * vec2, feed_dict={vec1: [1, 2], vec2: [3, 4]})

** VECTORS **************************************************
addition [4 6]
element-wise multiplication [3 8]
** MATRICES *************************************************
addition
[[  6.6   8.8]
 [ 11.   13.2]]
element-wise multiplication
[[  6.05  14.52]
 [ 25.41  38.72]]
matrix multiplication
[[ 22.99  26.62]
 [ 52.03  60.5 ]]


Reduce operations can be used to reduce vectors or matrix colums into single numbers: similar to python's `reduce` function.

In [7]:
# Python: reduce sum
print "Python reduce():", reduce(lambda x, y: x + y, [1, 2, 3])
# Tensorflow: reduce sum, reduce mean, etc
vec3 = tf.placeholder(dtype=np.int32)
print "Tensorflow tf.reduce_sum():", sess.run(tf.reduce_sum(vec3), {vec3: [1, 2, 3]})
print "Tensorflow tf.reduce_mean():", sess.run(tf.reduce_mean(vec3), {vec3: [1, 2, 3]})

# Reduce sum for matrix
mat3 = tf.placeholder(shape=(3, 2), dtype=np.int32)
print "\nMatrix tf.reduce_sum()"
# axis=0 => reduce colums: [1+3+5, 2+4+6] = [9, 12]
# axis=1 => reduce colums: [1+2, 3+4, 5+6] = [3, 7, 11]
# axis=None => reduce over axis 0, then reduce again: [1+3+5, 2+4+6] = [9, 12], [9+12] = 21
print "Tensorflow tf.reduce_sum(), axis=0:", sess.run(tf.reduce_sum(mat3, axis=0), {mat3: [[1, 2], [3, 4], [5, 6]]})
print "Tensorflow tf.reduce_sum(), axis=1:", sess.run(tf.reduce_sum(mat3, axis=1), {mat3: [[1, 2], [3, 4], [5, 6]]})
print "Tensorflow tf.reduce_sum(), axis=None:", sess.run(tf.reduce_sum(mat3, axis=None), {mat3: [[1, 2], [3, 4], [5, 6]]})

Python reduce(): 6
Tensorflow tf.reduce_sum(): 6
Tensorflow tf.reduce_mean(): 2

Matrix tf.reduce_sum()
Tensorflow tf.reduce_sum(), axis=0: [ 9 12]
Tensorflow tf.reduce_sum(), axis=1: [ 3  7 11]
Tensorflow tf.reduce_sum(), axis=None: 21


# Sessions and graphs

You can work with multiple sessions or multiple graphs 

In [10]:
with tf.Session() as sess2:
    foo = tf.constant(123)
    print sess2.run(foo)
    print sess2.graph.get_operations()
    


123
[<tf.Operation 'Const' type=Const>, <tf.Operation 'number1' type=Const>, <tf.Operation 'number2' type=Const>, <tf.Operation 'Add' type=Add>, <tf.Operation 'add' type=Add>, <tf.Operation 'Placeholder' type=Placeholder>, <tf.Operation 'Placeholder_1' type=Placeholder>, <tf.Operation 'add_1' type=Add>, <tf.Operation 'add_2' type=Add>, <tf.Operation 'Placeholder_2' type=Placeholder>, <tf.Operation 'Placeholder_3' type=Placeholder>, <tf.Operation 'add_3' type=Add>, <tf.Operation 'mul' type=Mul>, <tf.Operation 'Placeholder_4' type=Placeholder>, <tf.Operation 'Placeholder_5' type=Placeholder>, <tf.Operation 'add_4' type=Add>, <tf.Operation 'mul_1' type=Mul>, <tf.Operation 'MatMul' type=MatMul>, <tf.Operation 'Placeholder_6' type=Placeholder>, <tf.Operation 'Rank' type=Rank>, <tf.Operation 'range/start' type=Const>, <tf.Operation 'range/delta' type=Const>, <tf.Operation 'range' type=Range>, <tf.Operation 'Sum' type=Sum>, <tf.Operation 'Rank_1' type=Rank>, <tf.Operation 'range_1/start' type

Note that multiple sessions can reference the same graph. If you don't explicitely tell the **session** which **graph** to use, it will use the default graph. The result is that if you do multiple computations in tensorflow on this default graph, that there will be multiple disjointed subgraphs as part of it, one for each computation. This is why you see this many operations printed above.

In [12]:
# Using a seperate graph:
with tf.Session(graph=tf.Graph()) as sess3:
    bar = tf.constant(456)
    print sess3.run(bar)
    print sess3.graph.get_operations()

456
[<tf.Operation 'Const' type=Const>]
